title: kai.codes
description: "a beginner's journey in tech"
author:
  name: "Kai Rathmann"
  url: "https://kai.codes"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/
timezone: UTC

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Kai Rathmann"
year : "2019"
